Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-13"
    config.ssh.insert_key = true
    config.vm.boot_timeout = 600
    config.ssh.connect_timeout = 120

    # une seule VM serveur en p2
    config.vm.define "cpoulainS" do |server|
        server.vm.hostname = "cpoulainS"
        server.vm.network "private_network", ip: "192.168.56.110"

        server.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 1
            vb.name = "cpoulainS"
        end
        # install de k3s en mode serveur
        server.vm.provision "shell", path: "scripts/install_k3s_server.sh"

        # deploiement des applications et de l'ingress
        server.vm.provision "shell", path: "scripts/deploy_k3s.sh"

        # installation de kubectl et aliases
        server.vm.provision "shell", path: "scripts/install_kubectl.sh"

    end
end